name: kusto-language-server
description: kusto-language-server
homepage: https://github.com/rosshamish/kuskus/tree/master/kusto-language-server
licenses:
  - GPL-3.0-or-later
languages:
  - kusto
categories:
  - Formatter
  - LSP
  - Linter

source:
  # renovate:datasource=github-tags
  id: pkg:github/rosshamish/kuskus/tree/master/kusto-language-server
  build:
    run: |
      npm install
      npm run vscode:prepublish

bin:
  kusto-language-server: node:server/out/server.js --stdio
